modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/Gegy/whats-that-slot"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "What's That Slot"
authors = "Gegy"
description = '''
Utility that highlights which items can be placed in an item slot while holding down Left Alt.'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
