plugins {
  id 'fabric-loom'
}

base {
  archivesName = "$mod_file_name-fabric"
}

loom {
  mixin {
    defaultRefmapName.set("${mod_id}.refmap.json")
  }
  runs {
    client {
      client()
      setConfigName 'Fabric Client'
      ideConfigGenerated true
      runDir '../run'
    }
  }
  mods {
    "${mod_id}" {
      sourceSet project(':common').sourceSets.main
      sourceSet project.sourceSets.main
    }
  }
}

repositories {
  maven { url "https://maven.shedaniel.me" }
}

dependencies {
  implementation project(':common')

  minecraft "com.mojang:minecraft:$minecraft_version"
  mappings loom.layered {
    officialMojangMappings()
    parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
  }

  modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
  modImplementation(include(fabricApi.module("fabric-resource-loader-v0", fabric_version)))

  modCompileOnly "dev.architectury:architectury-fabric:$architectury_version"
  modCompileOnly "me.shedaniel.cloth:basic-math:$cloth_version"
  modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:$rei_version"
  modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"

  implementation 'com.google.code.findbugs:jsr305:3.0.1'
}

tasks.withType(JavaCompile).configureEach {
  source project(':common').sourceSets.main.allSource
}

processResources {
  from project(':common').sourceSets.main.resources
}
