# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod Properties
mod_version=1.3.7
release=true
maven_group=dev.gegy
mod_id=whats_that_slot
mod_file_name=whats-that-slot
mod_name=What's That Slot?
mod_author=Gegy
license=LGPLv3
credits=
description=Utility that highlights which items can be placed in an item slot while holding down Left Alt.
sources=https://github.com/Gegy/whats-that-slot
issue_tracker=https://github.com/Gegy/whats-that-slot/issues

minecraft_version=1.21.4
minecraft_version_range=1.21.4
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.4
parchment_version=2025.01.05

# Fabric - https://fabricmc.net/develop
fabric_version=0.118.0+1.21.4
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.4.101-beta
neoforge_loader_version_range=[2,)

rei_version=18.0.800
architectury_version=15.0.2
cloth_version=0.6.1
jei_version=19.21.0.247
jei_minecraft_version=1.21.1
