plugins {
  id 'net.neoforged.moddev'
}

base {
  archivesName = "$mod_id-common-$minecraft_version"
}

neoForge {
  neoFormVersion = neo_form_version
  parchment {
    minecraftVersion = minecraft_version
    mappingsVersion = parchment_version
  }

  ideSyncTask rootProject.tasks.named('generateModManifests')
}

dependencies {
  compileOnly 'org.spongepowered:mixin:0.8.5'
  compileOnly 'io.github.llamalad7:mixinextras-common:0.3.5'
  annotationProcessor 'io.github.llamalad7:mixinextras-common:0.3.5'

  implementation 'com.google.code.findbugs:jsr305:3.0.1'
}
