plugins {
  id 'net.neoforged.moddev'
}

base {
  archivesName = "$mod_file_name-neoforge"
}

neoForge {
  version = neoforge_version

  parchment {
    minecraftVersion = minecraft_version
    mappingsVersion = parchment_version
  }

  runs {
    configureEach {
      gameDirectory = rootProject.file('run')
      logLevel = org.slf4j.event.Level.WARN
    }
    client {
      client()
      programArguments.addAll '--username', 'Dev###'
    }
  }

  mods {
    "${mod_id}" {
      sourceSet project(':common').sourceSets.main
      sourceSet project.sourceSets.main
    }
  }
}

repositories {
  maven { url "https://dvs1.progwml6.com/files/maven/" }
  maven { url "https://modmaven.dev" }
}

dependencies {
  compileOnly project(":common")

  implementation "net.neoforged:neoforge:$neoforge_version"

  // TODO: Bring back when JEI is updated to 1.21.4
  // compileOnly "mezz.jei:jei-$jei_minecraft_version-common-api:$jei_version"
  // runtimeOnly "mezz.jei:jei-$jei_minecraft_version-neoforge:$jei_version"
}

tasks.named('compileJava', JavaCompile) {
  source project(':common').sourceSets.main.allSource
}

processResources {
  from project(':common').sourceSets.main.resources
}
